#ifndef countries_hh
#define countries_hh

constexpr char const *countries[] = {
	"AF - Afghanistan",
	"AL - Albania",
	"DZ - Algeria",
	"AD - Andorra",
	"AO - Angola",
	"AI - Anguilla",
	"AQ - Antartide",
	"AG - Antigua e Barbuda",
	"SA - Arabia Saudita",
	"AR - Argentina",
	"AM - Armenia",
	"AW - Aruba",
	"AU - Australia",
	"AT - Austria",
	"AZ - Azerbaigian",
	"BS - Bahamas",
	"BH - Bahrein",
	"BD - Bangladesh",
	"BB - Barbados",
	"BE - Belgio",
	"BZ - Belize",
	"BJ - Benin",
	"BM - Bermuda",
	"BT - Bhutan",
	"BY - Bielorussia",
	"MM - Birmania",
	"BO - Bolivia",
	"BA - Bosnia ed Erzegovina",
	"BW - Botswana",
	"BR - Brasile",
	"BN - Brunei",
	"BG - Bulgaria",
	"BF - Burkina Faso",
	"BI - Burundi",
	"KH - Cambogia",
	"CM - Camerun",
	"CA - Canada",
	"CV - Capo Verde",
	"TD - Ciad",
	"CL - Cile",
	"CN - Cina",
	"CY - Cipro",
	"VA - Città del Vaticano",
	"CO - Colombia",
	"KM - Comore",
	"KP - Corea del Nord",
	"KR - Corea del Sud",
	"CI - Costa d'Avorio",
	"CR - Costa Rica",
	"HR - Croazia",
	"CU - Cuba",
	"CW - Curaçao",
	"DK - Danimarca",
	"DM - Dominica",
	"EC - Ecuador",
	"EG - Egitto",
	"SV - El Salvador",
	"AE - Emirati Arabi Uniti",
	"ER - Eritrea",
	"EE - Estonia",
	"ET - Etiopia",
	"FJ - Figi",
	"PH - Filippine",
	"FI - Finlandia",
	"FR - Francia",
	"GA - Gabon",
	"GM - Gambia",
	"GE - Georgia",
	"GS - Georgia del Sud e isole Sandwich meridionali",
	"DE - Germania",
	"GH - Ghana",
	"JM - Giamaica",
	"JP - Giappone",
	"GI - Gibilterra",
	"DJ - Gibuti",
	"JO - Giordania",
	"GR - Grecia",
	"GD - Grenada",
	"GL - Groenlandia",
	"GP - Guadalupa",
	"GU - Guam",
	"GT - Guatemala",
	"GG - Guernsey",
	"GN - Guinea",
	"GQ - Guinea Equatoriale",
	"GW - Guinea-Bissau",
	"GY - Guyana",
	"GF - Guyana francese",
	"HT - Haiti",
	"HN - Honduras",
	"HK - Hong Kong",
	"IN - India",
	"ID - Indonesia",
	"IR - Iran",
	"IQ - Iraq",
	"IE - Irlanda",
	"XI - Irlanda del Nord",
	"IS - Islanda",
	"BV - Isola Bouvet",
	"CX - Isola del Natale",
	"IM - Isola di Man",
	"NF - Isola Norfolk",
	"AX - Isole Åland",
	"BQ - Isole BES",
	"KY - Isole Cayman",
	"CC - Isole Cocos e Keeling",
	"CK - Isole Cook",
	"FK - Isole Falkland",
	"FO - Isole Fær Øer",
	"HM - Isole Heard e McDonald",
	"MP - Isole Marianne Settentrionali",
	"MH - Isole Marshall",
	"UM - Isole minori esterne degli Stati Uniti",
	"PN - Isole Pitcairn",
	"SB - Isole Salomone",
	"TC - Isole Turks e Caicos",
	"VI - Isole Vergini americane",
	"VG - Isole Vergini britanniche",
	"IL - Israele",
	"IT - Italia",
	"JE - Jersey",
	"KZ - Kazakistan",
	"KE - Kenya",
	"KG - Kirghizistan",
	"KI - Kiribati",
	"XK - Kosovo",
	"KW - Kuwait",
	"LA - Laos",
	"LS - Lesotho",
	"LV - Lettonia",
	"LB - Libano",
	"LR - Liberia",
	"LY - Libia",
	"LI - Liechtenstein",
	"LT - Lituania",
	"LU - Lussemburgo",
	"MO - Macao",
	"MK - Macedonia",
	"MG - Madagascar",
	"MW - Malawi",
	"MV - Maldive",
	"MY - Malesia",
	"ML - Mali",
	"MT - Malta",
	"MA - Marocco",
	"MQ - Martinica",
	"MR - Mauritania",
	"MU - Mauritius",
	"YT - Mayotte",
	"MX - Messico",
	"MD - Moldavia",
	"MC - Monaco",
	"MN - Mongolia",
	"ME - Montenegro",
	"MS - Montserrat",
	"MZ - Mozambico",
	"NA - Namibia",
	"NR - Nauru",
	"NP - Nepal",
	"NI - Nicaragua",
	"NE - Niger",
	"NG - Nigeria",
	"NU - Niue",
	"NO - Norvegia",
	"NC - Nuova Caledonia",
	"NZ - Nuova Zelanda",
	"OM - Oman",
	"NL - Paesi Bassi",
	"PK - Pakistan",
	"PW - Palau",
	"PA - Panama",
	"PG - Papua Nuova Guinea",
	"PY - Paraguay",
	"PE - Perù",
	"PF - Polinesia Francese",
	"PL - Polonia",
	"PR - Porto Rico",
	"PT - Portogallo",
	"QA - Qatar",
	"GB - Regno Unito",
	"CZ - Repubblica Ceca",
	"CF - Repubblica Centrafricana",
	"CG - Repubblica del Congo",
	"CD - Repubblica Democratica del Congo",
	"TW - Repubblica di Cina",
	"DO - Repubblica Dominicana",
	"RE - Riunione",
	"RO - Romania",
	"RW - Ruanda",
	"RU - Russia",
	"EH - Sahara Occidentale",
	"KN - Saint Kitts e Nevis",
	"VC - Saint Vincent e Grenadine",
	"BL - Saint-Barthélemy",
	"MF - Saint-Martin",
	"PM - Saint-Pierre e Miquelon",
	"WS - Samoa",
	"AS - Samoa Americane",
	"SM - San Marino",
	"SH - Sant'Elena, Isola di Ascensione e Tristan da Cunha",
	"LC - Santa Lucia",
	"ST - São Tomé e Príncipe",
	"SN - Senegal",
	"RS - Serbia",
	"SC - Seychelles",
	"SL - Sierra Leone",
	"SG - Singapore",
	"SX - Sint Maarten",
	"SY - Siria",
	"SK - Slovacchia",
	"SI - Slovenia",
	"SO - Somalia",
	"ES - Spagna",
	"LK - Sri Lanka",
	"FM - Stati Federati di Micronesia",
	"US - Stati Uniti d'America",
	"PS - Stato di Palestina",
	"ZA - Sudafrica",
	"SD - Sudan",
	"SS - Sudan del Sud",
	"SR - Suriname",
	"SJ - Svalbard e Jan Mayen",
	"SE - Svezia",
	"CH - Svizzera",
	"SZ - Swaziland",
	"TJ - Tagikistan",
	"TZ - Tanzania",
	"IO - Territori Britannici dell'Oceano Indiano",
	"TF - Territori Francesi del Sud",
	"TH - Thailandia",
	"TL - Timor Est",
	"TG - Togo",
	"TK - Tokelau",
	"TO - Tonga",
	"TT - Trinidad e Tobago",
	"TN - Tunisia",
	"TR - Turchia",
	"TM - Turkmenistan",
	"TV - Tuvalu",
	"UA - Ucraina",
	"UG - Uganda",
	"HU - Ungheria",
	"UY - Uruguay",
	"UZ - Uzbekistan",
	"VU - Vanuatu",
	"VE - Venezuela",
	"VN - Vietnam",
	"WF - Wallis e Futuna",
	"YE - Yemen",
	"ZM - Zambia",
	"ZW - Zimbabwe",
	0,
};

#endif /* countries_hh */
